import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { motion } from "framer-motion";
import { TrendingUp } from "lucide-react";
import { AnimatedCounter } from "./AnimatedCounter";
import { useAnalytics } from "@/hooks/useCallAnalytics";
import { useDashboardMonth, ymLabel } from "./DashboardMonthContext";

export function RevenueChart() {
  const { revenueSeries, valueSummary: v } = useAnalytics();
  const { ym } = useDashboardMonth();
  const total = v.revenue;

  return (
    <div className="glass-card rounded-2xl p-6">
      <div className="grid grid-cols-[minmax(0,1fr)_auto] items-start gap-4 sm:flex sm:items-center sm:justify-between">
        <div className="min-w-0">
          <div className="flex items-center gap-2">
            <TrendingUp className="h-4 w-4 text-secondary" />
            <h3 className="text-sm font-semibold">Revenue generated by Atyvia</h3>
          </div>
          <div className="mt-2 flex items-baseline gap-3">
            <div className="text-3xl font-semibold tracking-tight">
              <AnimatedCounter value={total} prefix="£" />
            </div>
            <span className="text-xs text-muted-foreground">{ymLabel(ym)}</span>
          </div>
        </div>
      </div>

      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ duration: 0.6 }}
        className="mt-6 h-72"
      >
        <ResponsiveContainer width="100%" height="100%">
          <AreaChart data={revenueSeries} margin={{ top: 10, right: 8, left: -12, bottom: 0 }}>
            <defs>
              <linearGradient id="revGen" x1="0" y1="0" x2="0" y2="1">
                <stop offset="0%" stopColor="var(--color-secondary)" stopOpacity={0.35} />
                <stop offset="100%" stopColor="var(--color-secondary)" stopOpacity={0} />
              </linearGradient>
            </defs>
            <CartesianGrid stroke="var(--color-border)" strokeDasharray="3 6" vertical={false} />
            <XAxis dataKey="name" tick={{ fill: "var(--color-muted-foreground)", fontSize: 11 }} tickLine={false} axisLine={false} />
            <YAxis tick={{ fill: "var(--color-muted-foreground)", fontSize: 11 }} tickLine={false} axisLine={false} tickFormatter={(v) => `£${(v / 1000).toFixed(0)}k`} />
            <Tooltip
              cursor={{ stroke: "var(--color-border)", strokeWidth: 1 }}
              contentStyle={{
                background: "var(--color-popover)",
                border: "1px solid var(--color-border)",
                borderRadius: 12,
                fontSize: 12,
                boxShadow: "var(--shadow-elegant)",
              }}
              formatter={(val: number) => [`£${val.toLocaleString()}`, "Revenue"]}
            />
            <Area
              type="monotone"
              dataKey="generated"
              stroke="var(--color-secondary)"
              strokeWidth={2.4}
              fill="url(#revGen)"
              name="Revenue"
              dot={(props: { cx?: number; cy?: number; payload?: { isSelected?: boolean }; index?: number }) => {
                const { cx, cy, payload, index } = props;
                const selected = !!payload?.isSelected;
                return (
                  <circle
                    key={`dot-${index}`}
                    cx={cx}
                    cy={cy}
                    r={selected ? 5 : 3}
                    fill={selected ? "var(--color-secondary)" : "var(--color-background)"}
                    stroke="var(--color-secondary)"
                    strokeWidth={2}
                  />
                );
              }}
              activeDot={{ r: 6, fill: "var(--color-secondary)", stroke: "var(--color-background)", strokeWidth: 2 }}
            />
          </AreaChart>
        </ResponsiveContainer>
      </motion.div>

      <div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-3">
        <Metric label="Jobs booked" value={v.booked.toLocaleString()} hint="This month" />
        <Metric label="Revenue" value={`£${v.revenue.toLocaleString()}`} hint="Accepted quote value" />
        <Metric label="Your time saved" value={`${v.hoursSaved} hrs`} hint="This month" tone="secondary" />
      </div>
    </div>
  );
}

function Metric({ label, value, hint, tone }: { label: string; value: string; hint: string; tone?: "secondary" | "destructive" }) {
  return (
    <div className="rounded-xl border border-border/60 bg-muted/20 px-3 py-2.5">
      <p className="text-[10px] uppercase tracking-wider text-muted-foreground">{label}</p>
      <p
        className={
          "mt-1 text-base font-semibold tracking-tight" +
          (tone === "secondary" ? " text-secondary" : "") +
          (tone === "destructive" ? " text-destructive" : "")
        }
      >
        {value}
      </p>
      <p className="text-[10px] text-muted-foreground">{hint}</p>
    </div>
  );
}
