import { motion } from "framer-motion";
import { PoundSterling, Clock, Sparkles, CalendarCheck } from "lucide-react";
import { AnimatedCounter } from "./AnimatedCounter";
import { useAnalytics } from "@/hooks/useCallAnalytics";

export function ValueCalculator() {
  const { valueSummary: v, hasData } = useAnalytics();

  const stats = [
    { icon: CalendarCheck, label: "Jobs booked", value: v.booked, suffix: " jobs", tone: "secondary" as const },
    { icon: Clock, label: "Your time saved by", value: v.hoursSaved, suffix: " hrs" },
    { icon: PoundSterling, label: "Revenue generated by Atyvia", value: v.revenue, prefix: "£", tone: "secondary" as const },
  ];

  return (
    <div className="relative overflow-hidden rounded-2xl border border-primary/30 bg-gradient-to-br from-primary/20 via-background to-background p-6 shadow-[var(--shadow-elegant)]">
      <div className="pointer-events-none absolute -right-24 -top-24 h-64 w-64 rounded-full bg-secondary/20 blur-3xl" aria-hidden />
      <div className="pointer-events-none absolute -left-24 bottom-0 h-56 w-56 rounded-full bg-primary/20 blur-3xl" aria-hidden />

      <div className="relative flex flex-col gap-1">
        <h2 className="text-2xl font-semibold tracking-tight sm:text-3xl">
          Atyvia generated{" "}
          <span className="brand-highlight font-bold">
            <AnimatedCounter value={v.revenue} prefix="£" />
          </span>{" "}
          this period
        </h2>
        <p className="max-w-xl text-sm text-muted-foreground">
          {hasData
            ? `Based on ${v.booked.toLocaleString()} accepted quote${v.booked === 1 ? "" : "s"} booked as jobs this period.`
            : "Waiting for booking data — figures will populate automatically."}
        </p>
      </div>

      <div className="relative mt-6 grid gap-3 sm:grid-cols-3">
        {stats.map((s, i) => (
          <motion.div
            key={s.label}
            initial={{ opacity: 0, y: 12 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.4, delay: i * 0.06 }}
            className="rounded-xl border border-border/60 bg-background/40 p-4 backdrop-blur"
          >
            <div className="flex items-center gap-2 text-[11px] uppercase tracking-wider text-muted-foreground">
              <s.icon className={"h-3.5 w-3.5 " + (s.tone === "secondary" ? "text-secondary" : "text-primary")} />
              {s.label}
            </div>
            <div className="mt-2 text-2xl font-semibold tracking-tight">
              <AnimatedCounter value={s.value} prefix={s.prefix} suffix={s.suffix} />
            </div>
          </motion.div>
        ))}
      </div>
    </div>
  );
}
