/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignedOutRouteImport } from './routes/signed-out'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedRevenueRouteImport } from './routes/_authenticated/revenue'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedIntegrationsRouteImport } from './routes/_authenticated/integrations'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedCallsRouteImport } from './routes/_authenticated/calls'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedBusinessInfoRouteImport } from './routes/_authenticated/business-info'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedAppointmentsRouteImport } from './routes/_authenticated/appointments'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAiPerformanceRouteImport } from './routes/_authenticated/ai-performance'
import { Route as AuthenticatedBookingsIndexRouteImport } from './routes/_authenticated/bookings/index'
import { Route as QTokenBookRouteImport } from './routes/q.$token.book'
import { Route as ApiPublicTestQuoteEmailRouteImport } from './routes/api/public/test-quote-email'
import { Route as ApiPublicRetellWebhookRouteImport } from './routes/api/public/retell-webhook'
import { Route as AuthenticatedBookingsQuotesRouteImport } from './routes/_authenticated/bookings/quotes'
import { Route as AuthenticatedBookingsJobsRouteImport } from './routes/_authenticated/bookings/jobs'
import { Route as AuthenticatedBookingsInvoicesRouteImport } from './routes/_authenticated/bookings/invoices'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as ApiPublicQuotesRespondRouteImport } from './routes/api/public/quotes/respond'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicBrandingLogoSiteIdRouteImport } from './routes/api/public/branding/logo.$siteId'

const SignedOutRoute = SignedOutRouteImport.update({
  id: '/signed-out',
  path: '/signed-out',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRevenueRoute = AuthenticatedRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIntegrationsRoute =
  AuthenticatedIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCallsRoute = AuthenticatedCallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBusinessInfoRoute =
  AuthenticatedBusinessInfoRouteImport.update({
    id: '/business-info',
    path: '/business-info',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppointmentsRoute =
  AuthenticatedAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiPerformanceRoute =
  AuthenticatedAiPerformanceRouteImport.update({
    id: '/ai-performance',
    path: '/ai-performance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBookingsIndexRoute =
  AuthenticatedBookingsIndexRouteImport.update({
    id: '/bookings/',
    path: '/bookings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const QTokenBookRoute = QTokenBookRouteImport.update({
  id: '/q/$token/book',
  path: '/q/$token/book',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTestQuoteEmailRoute = ApiPublicTestQuoteEmailRouteImport.update({
  id: '/api/public/test-quote-email',
  path: '/api/public/test-quote-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRetellWebhookRoute = ApiPublicRetellWebhookRouteImport.update({
  id: '/api/public/retell-webhook',
  path: '/api/public/retell-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBookingsQuotesRoute =
  AuthenticatedBookingsQuotesRouteImport.update({
    id: '/bookings/quotes',
    path: '/bookings/quotes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBookingsJobsRoute =
  AuthenticatedBookingsJobsRouteImport.update({
    id: '/bookings/jobs',
    path: '/bookings/jobs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBookingsInvoicesRoute =
  AuthenticatedBookingsInvoicesRouteImport.update({
    id: '/bookings/invoices',
    path: '/bookings/invoices',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicQuotesRespondRoute = ApiPublicQuotesRespondRouteImport.update({
  id: '/api/public/quotes/respond',
  path: '/api/public/quotes/respond',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBrandingLogoSiteIdRoute =
  ApiPublicBrandingLogoSiteIdRouteImport.update({
    id: '/api/public/branding/logo/$siteId',
    path: '/api/public/branding/logo/$siteId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/signed-out': typeof SignedOutRoute
  '/ai-performance': typeof AuthenticatedAiPerformanceRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/appointments': typeof AuthenticatedAppointmentsRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/business-info': typeof AuthenticatedBusinessInfoRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/calls': typeof AuthenticatedCallsRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/revenue': typeof AuthenticatedRevenueRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/team': typeof AuthenticatedTeamRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/bookings/invoices': typeof AuthenticatedBookingsInvoicesRoute
  '/bookings/jobs': typeof AuthenticatedBookingsJobsRoute
  '/bookings/quotes': typeof AuthenticatedBookingsQuotesRoute
  '/api/public/retell-webhook': typeof ApiPublicRetellWebhookRoute
  '/api/public/test-quote-email': typeof ApiPublicTestQuoteEmailRoute
  '/q/$token/book': typeof QTokenBookRoute
  '/bookings/': typeof AuthenticatedBookingsIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/quotes/respond': typeof ApiPublicQuotesRespondRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/api/public/branding/logo/$siteId': typeof ApiPublicBrandingLogoSiteIdRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/signed-out': typeof SignedOutRoute
  '/ai-performance': typeof AuthenticatedAiPerformanceRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/appointments': typeof AuthenticatedAppointmentsRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/business-info': typeof AuthenticatedBusinessInfoRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/calls': typeof AuthenticatedCallsRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/revenue': typeof AuthenticatedRevenueRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/team': typeof AuthenticatedTeamRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/': typeof AuthenticatedIndexRoute
  '/bookings/invoices': typeof AuthenticatedBookingsInvoicesRoute
  '/bookings/jobs': typeof AuthenticatedBookingsJobsRoute
  '/bookings/quotes': typeof AuthenticatedBookingsQuotesRoute
  '/api/public/retell-webhook': typeof ApiPublicRetellWebhookRoute
  '/api/public/test-quote-email': typeof ApiPublicTestQuoteEmailRoute
  '/q/$token/book': typeof QTokenBookRoute
  '/bookings': typeof AuthenticatedBookingsIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/quotes/respond': typeof ApiPublicQuotesRespondRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/api/public/branding/logo/$siteId': typeof ApiPublicBrandingLogoSiteIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/signed-out': typeof SignedOutRoute
  '/_authenticated/ai-performance': typeof AuthenticatedAiPerformanceRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/appointments': typeof AuthenticatedAppointmentsRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/business-info': typeof AuthenticatedBusinessInfoRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/calls': typeof AuthenticatedCallsRoute
  '/_authenticated/customers': typeof AuthenticatedCustomersRoute
  '/_authenticated/integrations': typeof AuthenticatedIntegrationsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/revenue': typeof AuthenticatedRevenueRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/bookings/invoices': typeof AuthenticatedBookingsInvoicesRoute
  '/_authenticated/bookings/jobs': typeof AuthenticatedBookingsJobsRoute
  '/_authenticated/bookings/quotes': typeof AuthenticatedBookingsQuotesRoute
  '/api/public/retell-webhook': typeof ApiPublicRetellWebhookRoute
  '/api/public/test-quote-email': typeof ApiPublicTestQuoteEmailRoute
  '/q/$token/book': typeof QTokenBookRoute
  '/_authenticated/bookings/': typeof AuthenticatedBookingsIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/quotes/respond': typeof ApiPublicQuotesRespondRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/api/public/branding/logo/$siteId': typeof ApiPublicBrandingLogoSiteIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/contact'
    | '/signed-out'
    | '/ai-performance'
    | '/analytics'
    | '/appointments'
    | '/billing'
    | '/business-info'
    | '/calendar'
    | '/calls'
    | '/customers'
    | '/integrations'
    | '/profile'
    | '/reports'
    | '/revenue'
    | '/settings'
    | '/team'
    | '/checkout/return'
    | '/bookings/invoices'
    | '/bookings/jobs'
    | '/bookings/quotes'
    | '/api/public/retell-webhook'
    | '/api/public/test-quote-email'
    | '/q/$token/book'
    | '/bookings/'
    | '/api/public/payments/webhook'
    | '/api/public/quotes/respond'
    | '/lovable/email/transactional/preview'
    | '/api/public/branding/logo/$siteId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/contact'
    | '/signed-out'
    | '/ai-performance'
    | '/analytics'
    | '/appointments'
    | '/billing'
    | '/business-info'
    | '/calendar'
    | '/calls'
    | '/customers'
    | '/integrations'
    | '/profile'
    | '/reports'
    | '/revenue'
    | '/settings'
    | '/team'
    | '/checkout/return'
    | '/'
    | '/bookings/invoices'
    | '/bookings/jobs'
    | '/bookings/quotes'
    | '/api/public/retell-webhook'
    | '/api/public/test-quote-email'
    | '/q/$token/book'
    | '/bookings'
    | '/api/public/payments/webhook'
    | '/api/public/quotes/respond'
    | '/lovable/email/transactional/preview'
    | '/api/public/branding/logo/$siteId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/contact'
    | '/signed-out'
    | '/_authenticated/ai-performance'
    | '/_authenticated/analytics'
    | '/_authenticated/appointments'
    | '/_authenticated/billing'
    | '/_authenticated/business-info'
    | '/_authenticated/calendar'
    | '/_authenticated/calls'
    | '/_authenticated/customers'
    | '/_authenticated/integrations'
    | '/_authenticated/profile'
    | '/_authenticated/reports'
    | '/_authenticated/revenue'
    | '/_authenticated/settings'
    | '/_authenticated/team'
    | '/checkout/return'
    | '/_authenticated/'
    | '/_authenticated/bookings/invoices'
    | '/_authenticated/bookings/jobs'
    | '/_authenticated/bookings/quotes'
    | '/api/public/retell-webhook'
    | '/api/public/test-quote-email'
    | '/q/$token/book'
    | '/_authenticated/bookings/'
    | '/api/public/payments/webhook'
    | '/api/public/quotes/respond'
    | '/lovable/email/transactional/preview'
    | '/api/public/branding/logo/$siteId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  SignedOutRoute: typeof SignedOutRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  ApiPublicRetellWebhookRoute: typeof ApiPublicRetellWebhookRoute
  ApiPublicTestQuoteEmailRoute: typeof ApiPublicTestQuoteEmailRoute
  QTokenBookRoute: typeof QTokenBookRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  ApiPublicQuotesRespondRoute: typeof ApiPublicQuotesRespondRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  ApiPublicBrandingLogoSiteIdRoute: typeof ApiPublicBrandingLogoSiteIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signed-out': {
      id: '/signed-out'
      path: '/signed-out'
      fullPath: '/signed-out'
      preLoaderRoute: typeof SignedOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/revenue': {
      id: '/_authenticated/revenue'
      path: '/revenue'
      fullPath: '/revenue'
      preLoaderRoute: typeof AuthenticatedRevenueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/integrations': {
      id: '/_authenticated/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AuthenticatedIntegrationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calls': {
      id: '/_authenticated/calls'
      path: '/calls'
      fullPath: '/calls'
      preLoaderRoute: typeof AuthenticatedCallsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/business-info': {
      id: '/_authenticated/business-info'
      path: '/business-info'
      fullPath: '/business-info'
      preLoaderRoute: typeof AuthenticatedBusinessInfoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/appointments': {
      id: '/_authenticated/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AuthenticatedAppointmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-performance': {
      id: '/_authenticated/ai-performance'
      path: '/ai-performance'
      fullPath: '/ai-performance'
      preLoaderRoute: typeof AuthenticatedAiPerformanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bookings/': {
      id: '/_authenticated/bookings/'
      path: '/bookings'
      fullPath: '/bookings/'
      preLoaderRoute: typeof AuthenticatedBookingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/q/$token/book': {
      id: '/q/$token/book'
      path: '/q/$token/book'
      fullPath: '/q/$token/book'
      preLoaderRoute: typeof QTokenBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/test-quote-email': {
      id: '/api/public/test-quote-email'
      path: '/api/public/test-quote-email'
      fullPath: '/api/public/test-quote-email'
      preLoaderRoute: typeof ApiPublicTestQuoteEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/retell-webhook': {
      id: '/api/public/retell-webhook'
      path: '/api/public/retell-webhook'
      fullPath: '/api/public/retell-webhook'
      preLoaderRoute: typeof ApiPublicRetellWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/bookings/quotes': {
      id: '/_authenticated/bookings/quotes'
      path: '/bookings/quotes'
      fullPath: '/bookings/quotes'
      preLoaderRoute: typeof AuthenticatedBookingsQuotesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bookings/jobs': {
      id: '/_authenticated/bookings/jobs'
      path: '/bookings/jobs'
      fullPath: '/bookings/jobs'
      preLoaderRoute: typeof AuthenticatedBookingsJobsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bookings/invoices': {
      id: '/_authenticated/bookings/invoices'
      path: '/bookings/invoices'
      fullPath: '/bookings/invoices'
      preLoaderRoute: typeof AuthenticatedBookingsInvoicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/quotes/respond': {
      id: '/api/public/quotes/respond'
      path: '/api/public/quotes/respond'
      fullPath: '/api/public/quotes/respond'
      preLoaderRoute: typeof ApiPublicQuotesRespondRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/branding/logo/$siteId': {
      id: '/api/public/branding/logo/$siteId'
      path: '/api/public/branding/logo/$siteId'
      fullPath: '/api/public/branding/logo/$siteId'
      preLoaderRoute: typeof ApiPublicBrandingLogoSiteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAiPerformanceRoute: typeof AuthenticatedAiPerformanceRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedAppointmentsRoute: typeof AuthenticatedAppointmentsRoute
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedBusinessInfoRoute: typeof AuthenticatedBusinessInfoRoute
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedCallsRoute: typeof AuthenticatedCallsRoute
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRoute
  AuthenticatedIntegrationsRoute: typeof AuthenticatedIntegrationsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedRevenueRoute: typeof AuthenticatedRevenueRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedBookingsInvoicesRoute: typeof AuthenticatedBookingsInvoicesRoute
  AuthenticatedBookingsJobsRoute: typeof AuthenticatedBookingsJobsRoute
  AuthenticatedBookingsQuotesRoute: typeof AuthenticatedBookingsQuotesRoute
  AuthenticatedBookingsIndexRoute: typeof AuthenticatedBookingsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAiPerformanceRoute: AuthenticatedAiPerformanceRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedAppointmentsRoute: AuthenticatedAppointmentsRoute,
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedBusinessInfoRoute: AuthenticatedBusinessInfoRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedCallsRoute: AuthenticatedCallsRoute,
  AuthenticatedCustomersRoute: AuthenticatedCustomersRoute,
  AuthenticatedIntegrationsRoute: AuthenticatedIntegrationsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedRevenueRoute: AuthenticatedRevenueRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedBookingsInvoicesRoute: AuthenticatedBookingsInvoicesRoute,
  AuthenticatedBookingsJobsRoute: AuthenticatedBookingsJobsRoute,
  AuthenticatedBookingsQuotesRoute: AuthenticatedBookingsQuotesRoute,
  AuthenticatedBookingsIndexRoute: AuthenticatedBookingsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  SignedOutRoute: SignedOutRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  ApiPublicRetellWebhookRoute: ApiPublicRetellWebhookRoute,
  ApiPublicTestQuoteEmailRoute: ApiPublicTestQuoteEmailRoute,
  QTokenBookRoute: QTokenBookRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  ApiPublicQuotesRespondRoute: ApiPublicQuotesRespondRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  ApiPublicBrandingLogoSiteIdRoute: ApiPublicBrandingLogoSiteIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
